url: https://site-checker.rust.code-maven.com
repo: https://github.com/szabgab/site-checker.rs
branch: main
site_name: Site Checker
link_to_source: true
footer: The [Site Checker](https://github.com/szabgab/site-checker.rs).
tags:
  title: Tags
  description: Site Checker
from:
  name: Gabor Szabo
  email: gabor@szabgab.com
archive:
  title: Archive
  description: List of all the articles about the Site Checker
navbar:
  start:
    - path: /
      title: Home
  end:
    - path: /about
      title: About

